// Цветовые темы
export const themes = {
  blue: {
    primary: '#2c5f7c',
    secondary: '#6b8e9f',
    border: '#4a7c95',
    dateBg: 'linear-gradient(135deg, #e8f4f8 0%, #d4e8f0 100%)',
    taskBg: 'linear-gradient(to right, #f8fbfd 0%, white 100%)',
    line: '#a8c5d4',
    weekendBg: 'linear-gradient(135deg, #fff4e6 0%, #ffe8cc 100%)',
    weekendDateBg: 'linear-gradient(135deg, #ffd9a8 0%, #ffcc80 100%)',
    weekendColor: '#d67a00',
    holidayBg: 'linear-gradient(135deg, #ffe8f0 0%, #ffd4e5 100%)',
    holidayDateBg: 'linear-gradient(135deg, #ffb3d9 0%, #ff8cc7 100%)',
    holidayColor: '#cc0066',
  },
  green: {
    primary: '#2d7c4f',
    secondary: '#5a9d73',
    border: '#4a9d6a',
    dateBg: 'linear-gradient(135deg, #e8f8f0 0%, #d4f0e0 100%)',
    taskBg: 'linear-gradient(to right, #f8fdfb 0%, white 100%)',
    line: '#a8d4b8',
    weekendBg: 'linear-gradient(135deg, #fff0f5 0%, #ffe4ec 100%)',
    weekendDateBg: 'linear-gradient(135deg, #ffc4d6 0%, #ffaac7 100%)',
    weekendColor: '#c7366b',
    holidayBg: 'linear-gradient(135deg, #fff4e6 0%, #ffe8cc 100%)',
    holidayDateBg: 'linear-gradient(135deg, #ffd9a8 0%, #ffcc80 100%)',
    holidayColor: '#d67a00',
  },
  purple: {
    primary: '#6b4c9a',
    secondary: '#8b6bb7',
    border: '#8b6bb7',
    dateBg: 'linear-gradient(135deg, #f3eff8 0%, #e8dff5 100%)',
    taskBg: 'linear-gradient(to right, #faf8fd 0%, white 100%)',
    line: '#c4b4d9',
    weekendBg: 'linear-gradient(135deg, #fff8e6 0%, #ffedb3 100%)',
    weekendDateBg: 'linear-gradient(135deg, #ffe699 0%, #ffd966 100%)',
    weekendColor: '#cc9900',
    holidayBg: 'linear-gradient(135deg, #ffe8f0 0%, #ffd4e5 100%)',
    holidayDateBg: 'linear-gradient(135deg, #ffb3d9 0%, #ff8cc7 100%)',
    holidayColor: '#cc0066',
  },
  warm: {
    primary: '#c67a3e',
    secondary: '#d4954f',
    border: '#d4954f',
    dateBg: 'linear-gradient(135deg, #fdf5ef 0%, #faeadb 100%)',
    taskBg: 'linear-gradient(to right, #fdfaf8 0%, white 100%)',
    line: '#e8c9a8',
    weekendBg: 'linear-gradient(135deg, #f0e8ff 0%, #e4d4ff 100%)',
    weekendDateBg: 'linear-gradient(135deg, #d4b3ff 0%, #c299ff 100%)',
    weekendColor: '#7a3bcc',
    holidayBg: 'linear-gradient(135deg, #e8f8ff 0%, #d4f0ff 100%)',
    holidayDateBg: 'linear-gradient(135deg, #b3e0ff 0%, #80d4ff 100%)',
    holidayColor: '#0066cc',
  },
  mono: {
    primary: '#4a4a4a',
    secondary: '#6a6a6a',
    border: '#6a6a6a',
    dateBg: 'linear-gradient(135deg, #f5f5f5 0%, #e8e8e8 100%)',
    taskBg: 'linear-gradient(to right, #fafafa 0%, white 100%)',
    line: '#b8b8b8',
    weekendBg: 'linear-gradient(135deg, #e8e8e8 0%, #dddddd 100%)',
    weekendDateBg: 'linear-gradient(135deg, #d0d0d0 0%, #c5c5c5 100%)',
    weekendColor: '#5a5a5a',
    holidayBg: 'linear-gradient(135deg, #f8f8f8 0%, #eeeeee 100%)',
    holidayDateBg: 'linear-gradient(135deg, #d8d8d8 0%, #c8c8c8 100%)',
    holidayColor: '#3a3a3a',
  },
};

// Названия месяцев
export const monthNames = [
  'Январь',
  'Февраль',
  'Март',
  'Апрель',
  'Май',
  'Июнь',
  'Июль',
  'Август',
  'Сентябрь',
  'Октябрь',
  'Ноябрь',
  'Декабрь',
];

// Названия дней недели (короткие)
export const dayNames = ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'];

// Названия дней недели (полные)
export const dayNamesFull = [
  'Воскресенье',
  'Понедельник',
  'Вторник',
  'Среда',
  'Четверг',
  'Пятница',
  'Суббота',
];

// Данные о странах
export const countries = {
  russia: { nameKey: 'countryRussia', flag: '🇷🇺' },
  usa: { nameKey: 'countryUSA', flag: '🇺🇸' },
  uk: { nameKey: 'countryUK', flag: '🇬🇧' },
  germany: { nameKey: 'countryGermany', flag: '🇩🇪' },
  france: { nameKey: 'countryFrance', flag: '🇫🇷' },
  spain: { nameKey: 'countrySpain', flag: '🇪🇸' },
  italy: { nameKey: 'countryItaly', flag: '🇮🇹' },
  china: { nameKey: 'countryChina', flag: '🇨🇳' },
  japan: { nameKey: 'countryJapan', flag: '🇯🇵' },
};

// Дефолтные праздники по странам
export const defaultHolidays = {
  russia: [
    { date: '01-01', nameKey: 'holidayNewYear' },
    { date: '01-02', nameKey: 'holidayNewYearHolidays' },
    { date: '01-03', nameKey: 'holidayNewYearHolidays' },
    { date: '01-04', nameKey: 'holidayNewYearHolidays' },
    { date: '01-05', nameKey: 'holidayNewYearHolidays' },
    { date: '01-06', nameKey: 'holidayNewYearHolidays' },
    { date: '01-07', nameKey: 'holidayChristmas' },
    { date: '01-08', nameKey: 'holidayNewYearHolidays' },
    { date: '02-23', nameKey: 'holidayDefenderDay' },
    { date: '03-08', nameKey: 'holidayWomenDay' },
    { date: '05-01', nameKey: 'holidaySpringLabor' },
    { date: '05-09', nameKey: 'holidayVictoryDay' },
    { date: '06-12', nameKey: 'holidayRussiaDay' },
    { date: '11-04', nameKey: 'holidayUnityDay' },
  ],
  usa: [
    { date: '01-01', nameKey: 'holidayNewYear' },
    { date: '07-04', nameKey: 'holidayIndependenceDay' },
    { date: '12-25', nameKey: 'holidayChristmasDay' },
    { date: '11-11', nameKey: 'holidayVeteransDay' },
    { date: '02-14', nameKey: 'holidayValentinesDay' },
    { date: '10-31', nameKey: 'holidayHalloween' },
  ],
  uk: [
    { date: '01-01', nameKey: 'holidayNewYear' },
    { date: '12-25', nameKey: 'holidayChristmasDay' },
    { date: '12-26', nameKey: 'holidayBoxingDay' },
    { date: '03-17', nameKey: 'holidayStPatricksDay' },
  ],
  germany: [
    { date: '01-01', nameKey: 'holidayNewYearDE' },
    { date: '05-01', nameKey: 'holidayLaborDayDE' },
    { date: '10-03', nameKey: 'holidayGermanUnityDay' },
    { date: '12-25', nameKey: 'holidayChristmasDE' },
    { date: '12-26', nameKey: 'holidaySecondChristmasDay' },
  ],
  france: [
    { date: '01-01', nameKey: 'holidayNewYearFR' },
    { date: '05-01', nameKey: 'holidayLaborDayFR' },
    { date: '05-08', nameKey: 'holidayVictory1945' },
    { date: '07-14', nameKey: 'holidayNationalDay' },
    { date: '12-25', nameKey: 'holidayChristmasFR' },
  ],
  spain: [
    { date: '01-01', nameKey: 'holidayNewYearES' },
    { date: '01-06', nameKey: 'holidayThreeKingsDay' },
    { date: '05-01', nameKey: 'holidayLaborDayES' },
    { date: '10-12', nameKey: 'holidayNationalDayES' },
    { date: '12-25', nameKey: 'holidayChristmasES' },
  ],
  italy: [
    { date: '01-01', nameKey: 'holidayNewYearIT' },
    { date: '01-06', nameKey: 'holidayEpiphany' },
    { date: '04-25', nameKey: 'holidayLiberationDay' },
    { date: '05-01', nameKey: 'holidayLaborDayIT' },
    { date: '12-25', nameKey: 'holidayChristmasIT' },
  ],
  china: [
    { date: '01-01', nameKey: 'holidayNewYearCN' },
    { date: '05-01', nameKey: 'holidayLaborDayCN' },
    { date: '10-01', nameKey: 'holidayNationalDayCN' },
  ],
  japan: [
    { date: '01-01', nameKey: 'holidayNewYearJP' },
    { date: '02-11', nameKey: 'holidayFoundationDay' },
    { date: '05-03', nameKey: 'holidayConstitutionDay' },
    { date: '12-23', nameKey: 'holidayEmperorBirthday' },
  ],
};
